name: Publish @bechstein/prettier-config to NPM

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout-cone-mode: "true"
          sparse-checkout: packages/prettier-config

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://npm.pkg.github.com"

      - name: Publish to GitHub package registry
        run: npm publish --access public
        id: publish
        working-directory: packages/prettier-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check publish result
        if: steps.publish.outcome == 'failure'
        run: |
          echo "Publish failed. This might be because the version hasn't been updated."
          exit 0
