name: Publish @bechstein/eslint-config to npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Publish to GitHub package registry
        run: npm publish --access public
        id: publish
        working-directory: ./packages/eslint-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check publish result
        if: steps.publish.outcome == 'failure'
        run: |
          echo "Publish failed. This might be because the version hasn't been updated."
          exit 0
