name: Publish @bechstein/angular-eslint-config

on:
  push:
    branches:
      - main
    paths:
      - "packages/angular-eslint-config/**"

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout-cone-mode: "true"
          sparse-checkout: packages/angular-eslint-config

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
          cache-dependency-path: packages/angular-eslint-config/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub package registry
        run: npm publish --access public
        working-directory: packages/angular-eslint-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
